vim.keymap.set("n", "<leader>F", function() vim.lsp.buf.format({ async = true }) end)
vim.keymap.set('n', '<leader>rn', vim.lsp.buf.rename, { desc = "LSP Rename" })
-- Suggested mapping: Press 'Leader' then 'rn' to rename
require("lsp.basedpyright")
require("lsp.lua_ls")
require("lsp.bashls")
require("lsp.marksman")
require("lsp.tombi")
require("lsp.jinja_lsp")
require("lsp.vtsls")
require("lsp.ruff")
require("lsp.jsonls")
